export const GET_LOADING = 'GET_LOADING'

export const GET_EXERCISES = 'GET_EXERCISES'
export const GET_SETS = 'GET_SETS'
export const GET_LAST_SET = 'GET_LAST_SET'

export const GET_SNACKBAR = 'GET_SNACKBAR'
export const GET_SNACKBAR_MESSAGE = 'GET_SNACKBAR_MESSAGE'
export const GET_SNACKBAR_TYPE = 'GET_SNACKBAR_TYPE'
export const GET_SNACKBAR_TIMEOUT = 'GET_SNACKBAR_TIMEOUT'
